### ISSUE TITLE
camelcase 相关方法正则匹配无法匹配数值

### ISSUE THREAD

**Issue by nitta-honoka** [coderhaoxin/object-keys-mapping#14]
当需转换的字符串中带数字时，代码中所使用的正则匹配式无法匹配到，会造成转换错误。

如：

- `toCamelcase()` 转换 `str_a_10` 结果为 `strA_10`，期望结果为 `strA10`
- `reverseCamelcase()` 转换 `strA10` 结果为 `str_a10`, 期望结果为 `str_a_10`

**Comment by coderhaoxin** [comment]
3cd964d99b541df5857a772fe6d68e5aa75557f7

**Comment by coderhaoxin** [comment]
```
reverseCamelcase
```

不处理非常规数据, 例如: 'sendSMS' 等. 不具有规则通用性

**Comment by coderhaoxin** [comment]
💥 💥  warning!!! This is a broken version!
