### ISSUE TITLE
toCamelcase, reverseCamelcase - convert Date property to empty Object

### ISSUE THREAD

**Issue by newraina** [coderhaoxin/object-keys-mapping#17]
### input:

```js
toCamelcase({ time: new Date() })
```

### actual output:

```js
{ time: {} }
```

### expected output:

```js
{ time: Date('Wed May 30 2018 09:53:00 GMT+0800 (CST)') }
```

### reproduction:
https://codesandbox.io/embed/l7m95jkv27

### reason:
`isObject` should ignore Date、Error、null、Regxp Object

**Comment by coderhaoxin** [comment]
similar with #16

**Comment by coderhaoxin** [comment]
Just submit an invitation to you, you can push commits directly.
If you need to publish a new version, @ me to add you on npm.

**Comment by coderhaoxin** [comment]
fined by #18
